version: "1"
services:
  - type: pserv
    name: dgraph-standalone
    runtime: docker
    dockerfilePath: ./Dockerfile
    rootDir: dgraph
    plan: standard
    region: oregon
    disk:
      name: dgraph-data
      mountPath: /dgraph/data
      sizeGB: 10
    envVars:
      - key: PORT
        value: 8080
      - key: DGRAPH_ALPHA_BINDALL
        value: "true"
      - key: DGRAPH_TOKEN
        generateValue: true
      - key: API_TOKEN  # Additional token for custom middleware
        generateValue: true
  - type: web
    name: nginx-proxy
    runtime: docker
    dockerfilePath: ./Dockerfile
    rootDir: nginx-proxy
    plan: standard
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: api_token  # Lowercase for envsubst compatibility
        generateValue: true
      - key: dgraph_service_url  # Dynamic service URL with random suffix  
        fromService:
          type: pserv
          name: dgraph-standalone
          property: host